In [1]:
import pandas as pd
import numpy as np

### Q1. Pandas version

What version of Pandas did you install?

In [2]:
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count

How many records are in the dataset?

In [17]:
df.shape[0]

9704

### Q3. Fuel types

How many fuel types are presented in the dataset?

In [19]:
df.fuel_type.nunique()

2

### Q4. Missing values

How many columns in the dataset have missing values?



In [127]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [22]:
df[
    df.origin=='Asia'
    ].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

### Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.  
2. Next, calculate the most frequent value of the same horsepower column.  
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.  
4. Now, calculate the median value of horsepower once again.
  
Has it changed?

Yes, it increased  
Yes, it decreased  
No


In [61]:
df.horsepower.median()

np.float64(149.0)

In [62]:
df.horsepower.mode(dropna=True)

0    152.0
Name: horsepower, dtype: float64

In [63]:
hp = df.horsepower.fillna(152)

In [69]:
hp.median()

np.float64(152.0)

### Q7. Sum of weights

1. Select all the cars from Asia  
2. Select only columns vehicle_weight and model_year  
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?  
  
Note: You just implemented linear regression. We'll talk about it in the next lesson.  
  
0.051  
0.51  
5.1  
51  

In [114]:
df_asia = df[
    df.origin=='Asia'
    ]

df_asia = df_asia[['vehicle_weight', 'model_year']]


In [115]:
df_asia_seven = df_asia.head(7)
df_asia

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [116]:
X = df_asia_seven.to_numpy()

In [117]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [118]:
XTX = X.T.dot(X)

In [119]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [120]:
XTX_inv = np.linalg.inv(XTX)

In [121]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [122]:
X2 = XTX_inv.dot(X.T)

In [123]:
w = X2.dot(y)

In [124]:
w

array([0.01386421, 0.5049067 ])

In [125]:
w.sum()

np.float64(0.5187709081074016)